# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c3d1880f07608f71b8070bf11a2b237470c5fdfa56c0e3070e6b1d5a71acf0806919e8e908b628089895760a5bdd2ffd0cdba8728de63852dbc5da19709235f

test:
  secret_key_base: 2475e50de8b50c9d04624f84a3e2848e6a8f94e15f1ebb7d8e9a41d2950d38da089d561250f6a7363e20b3306ef5ac8cd1cb570519416ee350707c84eca11501

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
